package com.skapp.community.common.type;

public enum Role {

	SUPER_ADMIN, PEOPLE_ADMIN, PEOPLE_MANAGER, PEOPLE_EMPLOYEE, LEAVE_ADMIN, LEAVE_MANAGER, LEAVE_EMPLOYEE,
	ATTENDANCE_ADMIN, ATTENDANCE_MANAGER, ATTENDANCE_EMPLOYEE

}
