package com.skapp.community.peopleplanner.type;

public enum EmployeeTimelineType {

	JOB_FAMILY_CHANGED, JOB_FAMILY_ASSIGNED, JOB_TITLE_CHANGED, MANAGER_CHANGED, MANAGER_ASSIGNED, MANAGER_DELETED,
	DEPARTMENT_CHANGED, JOINED_DATE, TEAM_CHANGED, PROBATION_END_DATE, PROBATION_START_DATE, TEAM_REMOVED,
	TEAM_ASSIGNED, ENTITLEMENT_ADDED, ENTITLEMENT_CHANGED, SYSTEM_PERMISSION_GRANTED, SYSTEM_PERMISSION_CHANGED,
	JOINED_DATE_CHANGED, JOB_LEVEL_ASSIGNED, CUSTOM_ALLOCATION, EMPLOYMENT_TYPE_ADDED, EMPLOYMENT_TYPE_CHANGED,
	EMPLOYMENT_ALLOCATION_ADDED, EMPLOYMENT_ALLOCATION_CHANGED

}
