name: Format, Lint, Build and Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  format:
    name: Run Spring Java Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Validate Spring Java Formatter
        run: mvn spring-javaformat:validate

  checkstyle:
    name: Run Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Run Checkstyle
        run: mvn checkstyle:check

  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    needs:
      - format
      - checkstyle

    strategy:
      matrix:
        java-version: [21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Build the Project
        run: mvn -B clean package

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        java-version: [21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Run Tests
        run: mvn test
